### ISSUE TITLE
 A new array is created on every iteration

### ISSUE THREAD

**Issue by bitriddler** [andresroberto/filter-and-transform#1]
This line creates an array in every iteration

https://github.com/andresroberto/filter-and-transform/blob/1fd07591c5ef02fb4de99c9ae5cac8998f56d94d/index.js#L11

To decrease memory usage, might be better to change this to
```
acc.push(transformFn(curr));
```

**Comment by andresroberto** [comment]
You are right. And since the `initialValue` is `[]`  I see no harm in mutating it. Thanks!
